// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGd9EaUV0BjsPMjnEsr75YCggyTq28pnI',
    appId: '1:482244190419:web:002669e6c89d829af53426',
    messagingSenderId: '482244190419',
    projectId: 'ostad-16',
    authDomain: 'ostad-16.firebaseapp.com',
    storageBucket: 'ostad-16.appspot.com',
    measurementId: 'G-X4Q5PK88NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KRpzncEPUS2_Ncj6Ov5eXVNXhw9k-po',
    appId: '1:482244190419:android:08fa24958d8316baf53426',
    messagingSenderId: '482244190419',
    projectId: 'ostad-16',
    storageBucket: 'ostad-16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEO7SnFTaMnyatrjmUYV5M-p3tI47kyXw',
    appId: '1:482244190419:ios:6cd106e6c6a2a00cf53426',
    messagingSenderId: '482244190419',
    projectId: 'ostad-16',
    storageBucket: 'ostad-16.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEO7SnFTaMnyatrjmUYV5M-p3tI47kyXw',
    appId: '1:482244190419:ios:4cda9ec691ac2904f53426',
    messagingSenderId: '482244190419',
    projectId: 'ostad-16',
    storageBucket: 'ostad-16.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
